### PR TITLE
L-2911: Bug: Infrequent base64 encoded API responses from Clio cause errors in our response processing

### PR DESCRIPTION
**Pull request by amackera**
L-2911: Bug: Infrequent base64 encoded API responses from Clio cause errors in our response processing

## Goals

This PR (hopefully) fixes an issue that arises occasionally with the Clio API whereby it will return an atypical rate limit indication response.

### CODE REVIEW

**Review by nfranchise — APPROVED** [review]
👏 excited for this one

**Comment by amackera** [comment]
gonna merge it and pray
i have no way to test this

**Comment by nfranchise** [comment]
go buck and smerge it

**Comment by amackera** [comment]
I added a bit more to it just to make sure we are dealing with the rate limited response

**Pull request merged**
