### PR TITLE
L-1689 Bug fix for get_autopaginated_resource

### PR DESCRIPTION
**Pull request by nfranchise**
The problem seemed to be with a certain number of items (ie. contacts), the amount of requests grew to a point of hitting the rate limits and it looked like it was repeating some requests multiple times.

### CODE REVIEW

**Comment by amackera** [comment]
Oh did you just revert the auto page changes?

**Comment by nfranchise** [comment]
Yeah I took out the call back to get_paginated_resource because it seemed to just wreak havoc at bigger quantities. Not sure why though. 

I was trying to understand how it was meant to work, but I couldn't figure it out. Wouldn't it keep going back to get_autopaginated_resource every time? @amackera

**Comment by nfranchise** [comment]
Sorry, no, I didn't revert the changes. I just changed how the autopaginate function works. 

There are still the two functions. Autopaginate is there, just without the while loop that called back to 'get_paginated_resource' which then called 'get_autopaginated_resource'.

**Comment by amackera** [comment]
Ah thanks for the explanation @nfranchise, I think I see what the issue is. This fixed up implementation you wrote looks nice and simple (and correct!)

**Review by amackera — APPROVED** [review]
Thanks for the speedy fix @nfranchise. LGTM!

**Pull request merged**
